<?xml version="1.0"?>
<!DOCTYPE items [
<!ELEMENT items (item*)>
<!ATTLIST items burpVersion CDATA "">
<!ATTLIST items exportTime CDATA "">
<!ELEMENT item (time, url, host, port, protocol, method, path, extension, request, status, responselength, mimetype, response, comment)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT host (#PCDATA)>
<!ATTLIST host ip CDATA "">
<!ELEMENT port (#PCDATA)>
<!ELEMENT protocol (#PCDATA)>
<!ELEMENT method (#PCDATA)>
<!ELEMENT path (#PCDATA)>
<!ELEMENT extension (#PCDATA)>
<!ELEMENT request (#PCDATA)>
<!ATTLIST request base64 (true|false) "false">
<!ELEMENT status (#PCDATA)>
<!ELEMENT responselength (#PCDATA)>
<!ELEMENT mimetype (#PCDATA)>
<!ELEMENT response (#PCDATA)>
<!ATTLIST response base64 (true|false) "false">
<!ELEMENT comment (#PCDATA)>
]>
<items burpVersion="2025.10.1" exportTime="Mon Nov 10 11:14:05 IST 2025">
  <item>
    <time>Mon Nov 10 11:06:06 IST 2025</time>
    <url><![CDATA[http://localhost:3000/rest/products/5/reviews]]></url>
    <host ip="127.0.0.1">localhost</host>
    <port>3000</port>
    <protocol>http</protocol>
    <method><![CDATA[PUT]]></method>
    <path><![CDATA[/rest/products/5/reviews]]></path>
    <extension>null</extension>
    <request base64="true"><![CDATA[UFVUIC9yZXN0L3Byb2R1Y3RzLzUvcmV2aWV3cyBIVFRQLzEuMQ0KSG9zdDogbG9jYWxob3N0OjMwMDANCkNvbnRlbnQtTGVuZ3RoOiA1NA0Kc2VjLWNoLXVhLXBsYXRmb3JtOiAiTGludXgiDQpBdXRob3JpemF0aW9uOiBCZWFyZXIgZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKU1V6STFOaUo5LmV5SnpkR0YwZFhNaU9pSnpkV05qWlhOeklpd2laR0YwWVNJNmV5SnBaQ0k2TWpNc0luVnpaWEp1WVcxbElqb2lJaXdpWlcxaGFXd2lPaUo0YjI1dlpHVXhORFF3UUc1NVptaHJMbU52YlNJc0luQmhjM04zYjNKa0lqb2lZamd3TkRZeVpUWmlOVGsxTm1NNU56SmxNRGxqT0Rnd01tRTNNVGd6TjJJaUxDSnliMnhsSWpvaVkzVnpkRzl0WlhJaUxDSmtaV3gxZUdWVWIydGxiaUk2SWlJc0lteGhjM1JNYjJkcGJrbHdJam9pTUM0d0xqQXVNQ0lzSW5CeWIyWnBiR1ZKYldGblpTSTZJaTloYzNObGRITXZjSFZpYkdsakwybHRZV2RsY3k5MWNHeHZZV1J6TDJSbFptRjFiSFF1YzNabklpd2lkRzkwY0ZObFkzSmxkQ0k2SWlJc0ltbHpRV04wYVhabElqcDBjblZsTENKamNtVmhkR1ZrUVhRaU9pSXlNREkxTFRFeExUQTVJREExT2pJME9qTTRMalF3TUNBck1EQTZNREFpTENKMWNHUmhkR1ZrUVhRaU9pSXlNREkxTFRFeExUQTVJREExT2pJME9qTTRMalF3TUNBck1EQTZNREFpTENKa1pXeGxkR1ZrUVhRaU9tNTFiR3g5TENKcFlYUWlPakUzTmpJMk5qVTRPRGQ5LlNZblByYjZlY29IN1lGNTR0VXQwd0xPSmQ0SXpiMVNWR0dfNGpkc1dwTEc5TzVRUVRpalBCd195dGVIMFB4SlhUTVhJMFJnYVZTMzlrazdRLVFXRzZ0M0dSTnFVWERxcWlJakFHalVLMFMya1ZpdElRQW5Ick5HSnpCVTV0Q1Rfd3hEZk8yZGQyVTJnS0pwbE9oWHAwaWtNSlI4Z0kxeVpMSThoRXZOQkJ6OA0KQWNjZXB0LUxhbmd1YWdlOiBlbi1HQixlbjtxPTAuOQ0Kc2VjLWNoLXVhOiAiQ2hyb21pdW0iO3Y9IjE0MSIsICJOb3Q/QV9CcmFuZCI7dj0iOCINCnNlYy1jaC11YS1tb2JpbGU6ID8wDQpVc2VyLUFnZW50OiBNb3ppbGxhLzUuMCAoWDExOyBMaW51eCB4ODZfNjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS8xNDEuMC4wLjAgU2FmYXJpLzUzNy4zNg0KQWNjZXB0OiBhcHBsaWNhdGlvbi9qc29uLCB0ZXh0L3BsYWluLCAqLyoNCkNvbnRlbnQtVHlwZTogYXBwbGljYXRpb24vanNvbg0KT3JpZ2luOiBodHRwOi8vbG9jYWxob3N0OjMwMDANClNlYy1GZXRjaC1TaXRlOiBzYW1lLW9yaWdpbg0KU2VjLUZldGNoLU1vZGU6IGNvcnMNClNlYy1GZXRjaC1EZXN0OiBlbXB0eQ0KUmVmZXJlcjogaHR0cDovL2xvY2FsaG9zdDozMDAwLw0KQWNjZXB0LUVuY29kaW5nOiBnemlwLCBkZWZsYXRlLCBicg0KQ29va2llOiBsYW5ndWFnZT1lbjsgd2VsY29tZWJhbm5lcl9zdGF0dXM9ZGlzbWlzczsgY29va2llY29uc2VudF9zdGF0dXM9ZGlzbWlzczsgdG9rZW49ZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKU1V6STFOaUo5LmV5SnpkR0YwZFhNaU9pSnpkV05qWlhOeklpd2laR0YwWVNJNmV5SnBaQ0k2TWpNc0luVnpaWEp1WVcxbElqb2lJaXdpWlcxaGFXd2lPaUo0YjI1dlpHVXhORFF3UUc1NVptaHJMbU52YlNJc0luQmhjM04zYjNKa0lqb2lZamd3TkRZeVpUWmlOVGsxTm1NNU56SmxNRGxqT0Rnd01tRTNNVGd6TjJJaUxDSnliMnhsSWpvaVkzVnpkRzl0WlhJaUxDSmtaV3gxZUdWVWIydGxiaUk2SWlJc0lteGhjM1JNYjJkcGJrbHdJam9pTUM0d0xqQXVNQ0lzSW5CeWIyWnBiR1ZKYldGblpTSTZJaTloYzNObGRITXZjSFZpYkdsakwybHRZV2RsY3k5MWNHeHZZV1J6TDJSbFptRjFiSFF1YzNabklpd2lkRzkwY0ZObFkzSmxkQ0k2SWlJc0ltbHpRV04wYVhabElqcDBjblZsTENKamNtVmhkR1ZrUVhRaU9pSXlNREkxTFRFeExUQTVJREExT2pJME9qTTRMalF3TUNBck1EQTZNREFpTENKMWNHUmhkR1ZrUVhRaU9pSXlNREkxTFRFeExUQTVJREExT2pJME9qTTRMalF3TUNBck1EQTZNREFpTENKa1pXeGxkR1ZrUVhRaU9tNTFiR3g5TENKcFlYUWlPakUzTmpJMk5qVTRPRGQ5LlNZblByYjZlY29IN1lGNTR0VXQwd0xPSmQ0SXpiMVNWR0dfNGpkc1dwTEc5TzVRUVRpalBCd195dGVIMFB4SlhUTVhJMFJnYVZTMzlrazdRLVFXRzZ0M0dSTnFVWERxcWlJakFHalVLMFMya1ZpdElRQW5Ick5HSnpCVTV0Q1Rfd3hEZk8yZGQyVTJnS0pwbE9oWHAwaWtNSlI4Z0kxeVpMSThoRXZOQkJ6OA0KQ29ubmVjdGlvbjoga2VlcC1hbGl2ZQ0KDQp7Im1lc3NhZ2UiOiJ3ZXJ0dXVnZyIsImF1dGhvciI6Inhvbm9kZTE0NDBAbnlmaGsuY29tIn0=]]></request>
    <status>201</status>
    <responselength>409</responselength>
    <mimetype>JSON</mimetype>
    <response base64="true"><![CDATA[SFRUUC8xLjEgMjAxIENyZWF0ZWQNCkFjY2Vzcy1Db250cm9sLUFsbG93LU9yaWdpbjogKg0KWC1Db250ZW50LVR5cGUtT3B0aW9uczogbm9zbmlmZg0KWC1GcmFtZS1PcHRpb25zOiBTQU1FT1JJR0lODQpGZWF0dXJlLVBvbGljeTogcGF5bWVudCAnc2VsZicNClgtUmVjcnVpdGluZzogLyMvam9icw0KQ29udGVudC1UeXBlOiBhcHBsaWNhdGlvbi9qc29uOyBjaGFyc2V0PXV0Zi04DQpDb250ZW50LUxlbmd0aDogMjANCkVUYWc6IFcvIjE0LVk1M3d1RS9tbWJTaWtLY1QvV3VhbEwxTjY1VSINClZhcnk6IEFjY2VwdC1FbmNvZGluZw0KRGF0ZTogTW9uLCAxMCBOb3YgMjAyNSAwNTozNjowNiBHTVQNCkNvbm5lY3Rpb246IGtlZXAtYWxpdmUNCktlZXAtQWxpdmU6IHRpbWVvdXQ9NQ0KDQp7InN0YXR1cyI6InN1Y2Nlc3MifQ==]]></response>
    <comment></comment>
  </item>
  <item>
    <time>Mon Nov 10 11:06:40 IST 2025</time>
    <url><![CDATA[http://localhost:3000/rest/products/5/reviews]]></url>
    <host ip="127.0.0.1">localhost</host>
    <port>3000</port>
    <protocol>http</protocol>
    <method><![CDATA[PUT]]></method>
    <path><![CDATA[/rest/products/5/reviews]]></path>
    <extension>null</extension>
    <request base64="true"><![CDATA[UFVUIC9yZXN0L3Byb2R1Y3RzLzUvcmV2aWV3cyBIVFRQLzEuMQ0KSG9zdDogbG9jYWxob3N0OjMwMDANCkNvbnRlbnQtTGVuZ3RoOiA1MQ0Kc2VjLWNoLXVhLXBsYXRmb3JtOiAiTGludXgiDQpBdXRob3JpemF0aW9uOiBCZWFyZXIgZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKU1V6STFOaUo5LmV5SnpkR0YwZFhNaU9pSnpkV05qWlhOeklpd2laR0YwWVNJNmV5SnBaQ0k2TWpNc0luVnpaWEp1WVcxbElqb2lJaXdpWlcxaGFXd2lPaUo0YjI1dlpHVXhORFF3UUc1NVptaHJMbU52YlNJc0luQmhjM04zYjNKa0lqb2lZamd3TkRZeVpUWmlOVGsxTm1NNU56SmxNRGxqT0Rnd01tRTNNVGd6TjJJaUxDSnliMnhsSWpvaVkzVnpkRzl0WlhJaUxDSmtaV3gxZUdWVWIydGxiaUk2SWlJc0lteGhjM1JNYjJkcGJrbHdJam9pTUM0d0xqQXVNQ0lzSW5CeWIyWnBiR1ZKYldGblpTSTZJaTloYzNObGRITXZjSFZpYkdsakwybHRZV2RsY3k5MWNHeHZZV1J6TDJSbFptRjFiSFF1YzNabklpd2lkRzkwY0ZObFkzSmxkQ0k2SWlJc0ltbHpRV04wYVhabElqcDBjblZsTENKamNtVmhkR1ZrUVhRaU9pSXlNREkxTFRFeExUQTVJREExT2pJME9qTTRMalF3TUNBck1EQTZNREFpTENKMWNHUmhkR1ZrUVhRaU9pSXlNREkxTFRFeExUQTVJREExT2pJME9qTTRMalF3TUNBck1EQTZNREFpTENKa1pXeGxkR1ZrUVhRaU9tNTFiR3g5TENKcFlYUWlPakUzTmpJMk5qVTRPRGQ5LlNZblByYjZlY29IN1lGNTR0VXQwd0xPSmQ0SXpiMVNWR0dfNGpkc1dwTEc5TzVRUVRpalBCd195dGVIMFB4SlhUTVhJMFJnYVZTMzlrazdRLVFXRzZ0M0dSTnFVWERxcWlJakFHalVLMFMya1ZpdElRQW5Ick5HSnpCVTV0Q1Rfd3hEZk8yZGQyVTJnS0pwbE9oWHAwaWtNSlI4Z0kxeVpMSThoRXZOQkJ6OA0KQWNjZXB0LUxhbmd1YWdlOiBlbi1HQixlbjtxPTAuOQ0Kc2VjLWNoLXVhOiAiQ2hyb21pdW0iO3Y9IjE0MSIsICJOb3Q/QV9CcmFuZCI7dj0iOCINCnNlYy1jaC11YS1tb2JpbGU6ID8wDQpVc2VyLUFnZW50OiBNb3ppbGxhLzUuMCAoWDExOyBMaW51eCB4ODZfNjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS8xNDEuMC4wLjAgU2FmYXJpLzUzNy4zNg0KQWNjZXB0OiBhcHBsaWNhdGlvbi9qc29uLCB0ZXh0L3BsYWluLCAqLyoNCkNvbnRlbnQtVHlwZTogYXBwbGljYXRpb24vanNvbg0KT3JpZ2luOiBodHRwOi8vbG9jYWxob3N0OjMwMDANClNlYy1GZXRjaC1TaXRlOiBzYW1lLW9yaWdpbg0KU2VjLUZldGNoLU1vZGU6IGNvcnMNClNlYy1GZXRjaC1EZXN0OiBlbXB0eQ0KUmVmZXJlcjogaHR0cDovL2xvY2FsaG9zdDozMDAwLw0KQWNjZXB0LUVuY29kaW5nOiBnemlwLCBkZWZsYXRlLCBicg0KQ29va2llOiBsYW5ndWFnZT1lbjsgd2VsY29tZWJhbm5lcl9zdGF0dXM9ZGlzbWlzczsgY29va2llY29uc2VudF9zdGF0dXM9ZGlzbWlzczsgdG9rZW49ZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKU1V6STFOaUo5LmV5SnpkR0YwZFhNaU9pSnpkV05qWlhOeklpd2laR0YwWVNJNmV5SnBaQ0k2TWpNc0luVnpaWEp1WVcxbElqb2lJaXdpWlcxaGFXd2lPaUo0YjI1dlpHVXhORFF3UUc1NVptaHJMbU52YlNJc0luQmhjM04zYjNKa0lqb2lZamd3TkRZeVpUWmlOVGsxTm1NNU56SmxNRGxqT0Rnd01tRTNNVGd6TjJJaUxDSnliMnhsSWpvaVkzVnpkRzl0WlhJaUxDSmtaV3gxZUdWVWIydGxiaUk2SWlJc0lteGhjM1JNYjJkcGJrbHdJam9pTUM0d0xqQXVNQ0lzSW5CeWIyWnBiR1ZKYldGblpTSTZJaTloYzNObGRITXZjSFZpYkdsakwybHRZV2RsY3k5MWNHeHZZV1J6TDJSbFptRjFiSFF1YzNabklpd2lkRzkwY0ZObFkzSmxkQ0k2SWlJc0ltbHpRV04wYVhabElqcDBjblZsTENKamNtVmhkR1ZrUVhRaU9pSXlNREkxTFRFeExUQTVJREExT2pJME9qTTRMalF3TUNBck1EQTZNREFpTENKMWNHUmhkR1ZrUVhRaU9pSXlNREkxTFRFeExUQTVJREExT2pJME9qTTRMalF3TUNBck1EQTZNREFpTENKa1pXeGxkR1ZrUVhRaU9tNTFiR3g5TENKcFlYUWlPakUzTmpJMk5qVTRPRGQ5LlNZblByYjZlY29IN1lGNTR0VXQwd0xPSmQ0SXpiMVNWR0dfNGpkc1dwTEc5TzVRUVRpalBCd195dGVIMFB4SlhUTVhJMFJnYVZTMzlrazdRLVFXRzZ0M0dSTnFVWERxcWlJakFHalVLMFMya1ZpdElRQW5Ick5HSnpCVTV0Q1Rfd3hEZk8yZGQyVTJnS0pwbE9oWHAwaWtNSlI4Z0kxeVpMSThoRXZOQkJ6OA0KQ29ubmVjdGlvbjoga2VlcC1hbGl2ZQ0KDQp7Im1lc3NhZ2UiOiJnbyB0byBzbGVlcCIsImF1dGhvciI6InRhdGFAZ21haWwuY29tIn0=]]></request>
    <status>201</status>
    <responselength>409</responselength>
    <mimetype>JSON</mimetype>
    <response base64="true"><![CDATA[SFRUUC8xLjEgMjAxIENyZWF0ZWQNCkFjY2Vzcy1Db250cm9sLUFsbG93LU9yaWdpbjogKg0KWC1Db250ZW50LVR5cGUtT3B0aW9uczogbm9zbmlmZg0KWC1GcmFtZS1PcHRpb25zOiBTQU1FT1JJR0lODQpGZWF0dXJlLVBvbGljeTogcGF5bWVudCAnc2VsZicNClgtUmVjcnVpdGluZzogLyMvam9icw0KQ29udGVudC1UeXBlOiBhcHBsaWNhdGlvbi9qc29uOyBjaGFyc2V0PXV0Zi04DQpDb250ZW50LUxlbmd0aDogMjANCkVUYWc6IFcvIjE0LVk1M3d1RS9tbWJTaWtLY1QvV3VhbEwxTjY1VSINClZhcnk6IEFjY2VwdC1FbmNvZGluZw0KRGF0ZTogTW9uLCAxMCBOb3YgMjAyNSAwNTozNjo0MCBHTVQNCkNvbm5lY3Rpb246IGtlZXAtYWxpdmUNCktlZXAtQWxpdmU6IHRpbWVvdXQ9NQ0KDQp7InN0YXR1cyI6InN1Y2Nlc3MifQ==]]></response>
    <comment></comment>
  </item>
</items>
